# Generated by Django 5.0.7 on 2024-09-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_eventcenterpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcenterpayment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=50),
        ),
    ]
