# Generated by Django 5.0.7 on 2024-08-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0007_otphistory_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otphistory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'OTP Histories'},
        ),
        migrations.AddField(
            model_name='otphistory',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otphistory',
            name='otp',
            field=models.CharField(max_length=6),
        ),
    ]
