# Generated by Django 5.0.7 on 2024-09-04 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_centers', '0004_eventbooking_total_price'),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCenterFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_swimming_pool', models.BooleanField(default=False)),
                ('has_conference_room', models.BooleanField(default=False)),
                ('has_tennis_court', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='event_centers.eventcenter')),
            ],
            options={
                'verbose_name_plural': 'Event Center Facilities',
            },
        ),
    ]
