# Generated by Django 5.0.7 on 2024-08-03 13:16

import lib.path_and_rename
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, upload_to=lib.path_and_rename.HotelImageRename('hotel_images/')),
        ),
    ]
