# Generated by Django 5.0.7 on 2024-08-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_hotel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='country',
            field=models.CharField(choices=[('GH', 'Ghana')], default='GH', max_length=50),
        ),
    ]
