# Generated by Django 5.0.7 on 2024-08-05 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotel_country'),
        ('userprofile', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='userprofile.userprofile'),
        ),
    ]
