# Generated by Django 5.0.7 on 2024-08-06 19:33

import lib.path_and_rename
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=lib.path_and_rename.ProfileImageRename('profile_pics/')),
        ),
    ]
