# Generated by Django 5.0.7 on 2024-08-07 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0004_alter_hotel_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workhours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday', models.CharField(max_length=30)),
                ('monday', models.CharField(max_length=30)),
                ('tuesday', models.CharField(max_length=30)),
                ('wednesday', models.CharField(max_length=30)),
                ('thursday', models.CharField(max_length=30)),
                ('friday', models.CharField(max_length=30)),
                ('saturday', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workhours', to='hotels.hotel')),
            ],
        ),
    ]
