# Generated by Django 5.0.7 on 2024-09-04 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_centers', '0004_eventbooking_total_price'),
        ('workhours', '0002_alter_workhours_options_alter_workhours_friday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCenterWorkhours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday', models.CharField(default='8:00am - 6:00pm', max_length=30)),
                ('monday', models.CharField(default='8:00am - 6:00pm', max_length=30)),
                ('tuesday', models.CharField(default='8:00am - 6:00pm', max_length=30)),
                ('wednesday', models.CharField(default='8:00am - 6:00pm', max_length=30)),
                ('thursday', models.CharField(default='8:00am - 6:00pm', max_length=30)),
                ('friday', models.CharField(default='8:00am - 6:00pm', max_length=30)),
                ('saturday', models.CharField(default='8:00am - 6:00pm', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workhours', to='event_centers.eventcenter')),
            ],
            options={
                'verbose_name_plural': 'Event Center Working Hours',
            },
        ),
    ]
