# Generated by Django 5.0.7 on 2024-08-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_centers', '0002_eventbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbooking',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='number_of_guests',
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='special_requests',
        ),
        migrations.AddField(
            model_name='eventcenter',
            name='number_of_occupants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventcenter',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
