# Generated by Django 5.0.7 on 2024-09-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_centers', '0004_eventbooking_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventbooking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Event Center Booking', 'verbose_name_plural': 'Event Center Bookings'},
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='booking_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
