# Generated by Django 5.0.7 on 2024-08-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
