# Generated by Django 5.0.7 on 2024-08-22 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_checkin_alter_booking_checkout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Hotel Booking', 'verbose_name_plural': 'Hotel Bookings'},
        ),
    ]
